name = "SNNLab"
uuid = "df4ec7c9-ab53-4648-8e3a-80f944e880df"
authors = ["Akihiro Nakamura <nakamura27@bpe.es.osaka-u.ac.jp> and contributors"]
version = "1.0.0-DEV"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
